# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abef50d3e823d6dc74a63b7439a5663627db77e30aca796f3e9ffa7db2a702c2b03a77d7927c711da8610c1a90e268e124bd4c6cb478c97cc31039d006ebedb3

test:
  secret_key_base: 19c33245c5d264809c9373ed34bb9f06fd390f3e619d1047d0f2c813663fc01291260492f2ae7cb0688dca2871b8989350ee6e3da891bbde9d77b436d8848e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
